In [57]:
#Binary search
#this initial method is bad as it manipulates the array rather than just the index.
#it would not scale up well. The solution provided in the next cell is far better.
#It makes much more sense to use the indexes only in basic one off searches.

def binary_search(input_array, value):
    """Returns the index of 'value' in the input array 
    or -1 if value is not contained under the condition
    that the input array contains no duplicates and is in ascending order"""
    temp_index = 0
    arr_len = len(input_array)
    counter=0
    
    while arr_len > 1 and counter < 5:
        counter +=1

        arr_len = len(input_array)
        if arr_len % 2 == 0:
            halfway = (arr_len -1 )//2 
        else:
            halfway = arr_len //2 
        
        if input_array[halfway] == value:
            temp_index += halfway
            return temp_index
        
        elif input_array[halfway] > value:
            input_array = input_array[:halfway]
        else:
            temp_index += halfway +1
            input_array = input_array[halfway +1:]

    return -1

test_list = [1,3,9,11,15,19,29]
test_val1 = 25
test_val2 = 15

print(binary_search(test_list, test_val1))
print(binary_search(test_list, 1))
print(binary_search(test_list, test_val2))
print(binary_search(test_list, 11))
print(binary_search(test_list, 29))
test_list.append(40)
print(binary_search(test_list, test_val2))
print(binary_search(test_list, 11))
print(binary_search(test_list, 40))

0
-1
4
3
6
4
3
7


In [67]:
def binary_search(input_array, value):
    """Returns the index of 'value' in the input array 
    or -1 if value is not contained under the condition
    that the input array contains no duplicates and is in ascending order"""
    low = 0
    high = len(input_array) - 1
    
    while (low <= high):
        mid = (low + high)//2
        if (input_array[mid] == value):
            return mid
        elif (input_array[mid] < value):
            low = mid + 1
        else:
            high = mid -1
    return -1

print(binary_search(test_list, test_val1))
print(binary_search(test_list, 1))
print(binary_search(test_list, test_val2))
print(binary_search(test_list, 11))
print(binary_search(test_list, 29))
test_list.append(40)
print(binary_search(test_list, test_val2))
print(binary_search(test_list, 11))
print(binary_search(test_list, 40))

-1
0
4
3
6
4
3
7


The code given for the recursion example appears to be javascript, which is somewhat odd given that were doing python. The example is below, I'll refactor it into python for practice.

    function getFib(position) {
      if (position == 0) { return 0; }
      if (position == 1) { return 1; }
      var first = 0,
          second = 1,
          next = first + second;
      for (var i = 2; i < position; i++) {
        first = second;
        second = next;
        next = first + second;
      }
      return next;
    }

In [77]:
#refactored example:

def get_fib(position):
    '''Return the fibonacci sequence value at the given position
    of the fibanocci series'''
    
    if position ==0:
        return 0
    if position == 1:
        return 1
    
    first, second = 0, 1
    next_val = first + second
    
    for i in range(2,position):
        first = second
        second = next_val
        next_val = first + second
        
    return next_val
    
assert get_fib(0) == 0
assert get_fib(1) == 1
assert get_fib(2) == 1
assert get_fib(5) == 5
assert get_fib(8) == 21
    

In [83]:
def get_fib2(position):
    '''Return the fibonacci sequence value at the given position
    of the fibanocci series using recursion to calculated it'''
    
    if position <=0:
        value = 0
    elif position == 1:
        value = 1
    else:
        value = get_fib2(position-1) + get_fib2(position-2)
    
    return value

assert get_fib2(0) == 0
assert get_fib2(1) == 1
assert get_fib2(2) == 1
assert get_fib2(5) == 5
assert get_fib2(8) == 21
    

In [85]:
def get_fib2(position):
    '''Udacity provided example for recursion'''
    
    if position == 0 or position == 1:
        return position
    return get_fib(position - 1) + get_fib(position - 2)

assert get_fib2(0) == 0
assert get_fib2(1) == 1
assert get_fib2(2) == 1
assert get_fib2(5) == 5
assert get_fib2(8) == 21

In [117]:
#naive bubble sort implementation
import numpy as np

sorted_array = np.arange(2,20)
print(sorted_array)
unsorted_array = np.random.permutation(sorted_array)
print(unsorted_array)

def bubble_sort(arr):
    
    for i,_ in enumerate(arr):
        for j in range(len(arr)-1-i):

            if arr[j] > arr[j+1]:
                temp = arr[j+1]
                arr[j+1] = arr[j]
                arr[j] = temp
    return arr
            

print(bubble_sort(unsorted_array))

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2 18 19 12  8  6  4 15  7 16 10  5 11 14  9 13 17  3]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# selection sort

In [150]:
sorted_array = np.arange(2,20)
print(sorted_array)
unsorted_array = np.random.permutation(sorted_array)
print(unsorted_array)

def selection_sort(arr):
    n = len(arr)
    
    for i in range(n-1):
        low_idx = i
        current_low = arr[low_idx]
        
        for j in range(i+1,n):
            if arr[j] < current_low:
                low_idx = j
                current_low = arr[j]
        
        temp = arr[i]
        arr[i] = current_low
        arr[low_idx] = temp
    
    return arr
            
print(selection_sort(unsorted_array))
print(unsorted_array)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 19  5 15 14  2 11 18  9 16 13 12  4  7  6  8  3 17]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [226]:
def insertion_sort(arr):
    n = len(arr)
    for pivot in range(1,n):
        
        temp = arr[pivot]
        
        for j in reversed(range(pivot+1)):

            if arr[j-1] > temp:
                arr[j] = arr[j-1]
            else:
                break
                
        arr[j] = temp

    return arr

In [ ]:
def insertion_sort2(arr):
    n = len(arr)
    for pivot in range(1,n):
        j = pivot
        while j > 0 and arr[j-1] > temp:
                arr[j] = arr[j-1]
                j += -1
        arr[j] = temp
    return arr

In [225]:
sorted_array = np.arange(2,20)
print(sorted_array)
unsorted_array = np.random.permutation(sorted_array)
print(unsorted_array)
print('sorted:')
print(insertion_sort(unsorted_array))

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 8  7  3 12  2 18 19 17 15 14  9  5 16 10 11  4 13  6]
sorted:
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
