In [57]:
#Binary search
#this initial method is bad as it manipulates the array rather than just the index.
#it would not scale up well. The solution provided in the next cell is far better.
#It makes much more sense to use the indexes only in basic one off searches.

def binary_search(input_array, value):
    """Returns the index of 'value' in the input array 
    or -1 if value is not contained under the condition
    that the input array contains no duplicates and is in ascending order"""
    temp_index = 0
    arr_len = len(input_array)
    counter=0
    
    while arr_len > 1 and counter < 5:
        counter +=1

        arr_len = len(input_array)
        if arr_len % 2 == 0:
            halfway = (arr_len -1 )//2 
        else:
            halfway = arr_len //2 
        
        if input_array[halfway] == value:
            temp_index += halfway
            return temp_index
        
        elif input_array[halfway] > value:
            input_array = input_array[:halfway]
        else:
            temp_index += halfway +1
            input_array = input_array[halfway +1:]

    return -1

test_list = [1,3,9,11,15,19,29]
test_val1 = 25
test_val2 = 15

print(binary_search(test_list, test_val1))
print(binary_search(test_list, 1))
print(binary_search(test_list, test_val2))
print(binary_search(test_list, 11))
print(binary_search(test_list, 29))
test_list.append(40)
print(binary_search(test_list, test_val2))
print(binary_search(test_list, 11))
print(binary_search(test_list, 40))

0
-1
4
3
6
4
3
7


In [67]:
def binary_search(input_array, value):
    """Returns the index of 'value' in the input array 
    or -1 if value is not contained under the condition
    that the input array contains no duplicates and is in ascending order"""
    low = 0
    high = len(input_array) - 1
    
    while (low <= high):
        mid = (low + high)//2
        if (input_array[mid] == value):
            return mid
        elif (input_array[mid] < value):
            low = mid + 1
        else:
            high = mid -1
    return -1

print(binary_search(test_list, test_val1))
print(binary_search(test_list, 1))
print(binary_search(test_list, test_val2))
print(binary_search(test_list, 11))
print(binary_search(test_list, 29))
test_list.append(40)
print(binary_search(test_list, test_val2))
print(binary_search(test_list, 11))
print(binary_search(test_list, 40))

-1
0
4
3
6
4
3
7


The code given for the recursion example appears to be javascript, which is somewhat odd given that were doing python. The example is below, I'll refactor it into python for practice.

    function getFib(position) {
      if (position == 0) { return 0; }
      if (position == 1) { return 1; }
      var first = 0,
          second = 1,
          next = first + second;
      for (var i = 2; i < position; i++) {
        first = second;
        second = next;
        next = first + second;
      }
      return next;
    }

In [77]:
#refactored example:

def get_fib(position):
    '''Return the fibonacci sequence value at the given position
    of the fibanocci series'''
    
    if position ==0:
        return 0
    if position == 1:
        return 1
    
    first, second = 0, 1
    next_val = first + second
    
    for i in range(2,position):
        first = second
        second = next_val
        next_val = first + second
        
    return next_val
    
assert get_fib(0) == 0
assert get_fib(1) == 1
assert get_fib(2) == 1
assert get_fib(5) == 5
assert get_fib(8) == 21
    

In [83]:
def get_fib2(position):
    '''Return the fibonacci sequence value at the given position
    of the fibanocci series using recursion to calculated it'''
    
    if position <=0:
        value = 0
    elif position == 1:
        value = 1
    else:
        value = get_fib2(position-1) + get_fib2(position-2)
    
    return value

assert get_fib2(0) == 0
assert get_fib2(1) == 1
assert get_fib2(2) == 1
assert get_fib2(5) == 5
assert get_fib2(8) == 21
    

In [85]:
def get_fib2(position):
    '''Udacity provided example for recursion'''
    
    if position == 0 or position == 1:
        return position
    return get_fib(position - 1) + get_fib(position - 2)

assert get_fib2(0) == 0
assert get_fib2(1) == 1
assert get_fib2(2) == 1
assert get_fib2(5) == 5
assert get_fib2(8) == 21

In [117]:
#naive bubble sort implementation
import numpy as np

sorted_array = np.arange(2,20)
print(sorted_array)
unsorted_array = np.random.permutation(sorted_array)
print(unsorted_array)

def bubble_sort(arr):
    
    for i,_ in enumerate(arr):
        for j in range(len(arr)-1-i):

            if arr[j] > arr[j+1]:
                temp = arr[j+1]
                arr[j+1] = arr[j]
                arr[j] = temp
    return arr
            

print(bubble_sort(unsorted_array))

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2 18 19 12  8  6  4 15  7 16 10  5 11 14  9 13 17  3]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# selection sort

In [150]:
sorted_array = np.arange(2,20)
print(sorted_array)
unsorted_array = np.random.permutation(sorted_array)
print(unsorted_array)

def selection_sort(arr):
    n = len(arr)
    
    for i in range(n-1):
        low_idx = i
        current_low = arr[low_idx]
        
        for j in range(i+1,n):
            if arr[j] < current_low:
                low_idx = j
                current_low = arr[j]
        
        temp = arr[i]
        arr[i] = current_low
        arr[low_idx] = temp
    
    return arr
            
print(selection_sort(unsorted_array))
print(unsorted_array)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 19  5 15 14  2 11 18  9 16 13 12  4  7  6  8  3 17]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [226]:
def insertion_sort(arr):
    n = len(arr)
    for pivot in range(1,n):
        
        temp = arr[pivot]
        
        for j in reversed(range(pivot+1)):

            if arr[j-1] > temp:
                arr[j] = arr[j-1]
            else:
                break
                
        arr[j] = temp

    return arr

In [229]:
def insertion_sort2(arr):
    n = len(arr)
    for pivot in range(1,n):
        j = pivot
        temp = arr[pivot]
        
        while j > 0 and arr[j-1] > temp:
                arr[j] = arr[j-1]
                j += -1
        arr[j] = temp
    return arr

In [230]:
sorted_array = np.arange(2,20)
print(sorted_array)
unsorted_array = np.random.permutation(sorted_array)
print(unsorted_array)
print('sorted:')
print(insertion_sort2(unsorted_array))

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 13 18 16  6  2 12  5  9  8 11 14  4  3 10 17 15  7]
sorted:
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#https://www.khanacademy.org/computing/computer-science/algorithms/merge-sort/p/challenge-implement-merge-sort

# var mergeSort = function(array, p, r) {
#     if (p < r) {
#         var q = Math.floor((p + r) / 2);
#         mergeSort(array, p, q);
#         mergeSort(array, q+1, r);
#         merge(array, p, q, r);
#     }
# };

#merge function(array, p, q, r)
    #copy array[p:q] to low array, array[q+1:r] to high array
    
    #initialize vars
    i, j = 0,0
    k = p
    #while i less than or equal to q-p and j less than or equal to r-q+1
        #compared i and jth position in low half to high half
            #whichever is lower put in k, inc k, inc whichever was lower
    #check if i, j, less than q, r:
        #add remaining list if less than
        
        
# var merge = function(array, p, q, r) {
#     var lowHalf = [];
#     var highHalf = [];

#     var k = p;
#     var i;
#     var j;
#     for (i = 0; k <= q; i++, k++) {
#         lowHalf[i] = array[k];
#     }
#     for (j = 0; k <= r; j++, k++) {
#         highHalf[j] = array[k];
#     }

#     k = p;
#     i = 0;
#     j = 0;
    
#     // Repeatedly compare the lowest untaken element in
#     //  lowHalf with the lowest untaken element in highHalf
#     //  and copy the lower of the two back into array
#     while (i < q - p + 1 && j < r - q){
 
#         if (lowHalf[i] < highHalf[j]){
#          array[k] = lowHalf[i];
#          i++;
#          k++;
#         } else {
#          array[k] = highHalf[j];
#          j++;
#          k++;
#         }
#     }
    
#     while(i < q - p + 1) {
#         array[k] = lowHalf[i];
#          i++;
#          k++;
#     }
    
#     while( j < r - q){
#         array[k] = highHalf[j];
#         j++;
#         k++;
        
#     }

In [290]:
#python merge sort

def merge_sort(array):
    p = 0
    r = len(array) -1
    merge_sort_(array, p, r)

def merge_sort_(array, p, r):
    #divide array, define a pivot point
    if p < r:
        q = (p + r) // 2
        #call mergeSort on each half
        merge_sort_(array, p, q )
        merge_sort_(array, q+1, r)
        #merge each half
        ms_merge(array, p, q, r)

def ms_merge(array, p, q, r):
    #copy arrays to low and high
    low_half = [val for val in array[p:q+1]]
    high_half = [val for val in array[q+1:r+1]]
    #until one half used up, compare values put in array

    i, j = 0, 0
    k = p
    while (i < q - p + 1 and j < r - q):
        if (low_half[i] < high_half[j]):
            array[k] = low_half[i]
            i += 1
            k += 1
        else:
            array[k] = high_half[j]
            j += 1
            k += 1
    #put in remaining values for other half
    while (i <  q - p + 1):
        array[k] = low_half[i]
        i += 1
        k += 1

    while (j < r - q):
        array[k] = high_half[j]
        j += 1
        k += 1
    
    

In [299]:
sorted_array = np.arange(2,20)
sorted_array[0] = -5
unsorted_array = np.random.permutation(sorted_array.copy())
print(unsorted_array)
print(sorted_array)

merge_sort(unsorted_array)
print(unsorted_array)
assert np.array_equal(unsorted_array, sorted_array)

[17  7  4  5 19 15 14 -5 16 10 12  8  9 18  3  6 13 11]
[-5  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-5  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#quick sort from khan academy
#https://www.khanacademy.org/computing/computer-science/algorithms/quick-sort/a/overview-of-quicksort
# // This function partitions given array and returns 
# //  the index of the pivot.
# var partition=function(array, p, r){
#     // This code has been purposefully obfuscated,
#     // as you will implement it yourself in next challenge
#     var e=array,t=p,n=r;var r=function(e,t,n){var r=e[t];e[t]=e[n];e[n]=r;};var i=t;for(var s=t;s<n;s++){if(e[s]<=e[n]){r(e,s,i);i++;}}r(e,n,i);return i;
# };


# var quickSort = function(array, p, r) {
#     if (p < r) {
#     var pivot = partition(array, p, r);
#     quickSort(array, p, pivot-1);
#     quickSort(array, pivot+1, r);
    
#     }
    
# };

# var array = [9, 7, 5, 11, 12, 2, 14, 3, 10, 6];
# quickSort(array, 0, array.length-1);
# println("Array after sorting: " + array);
# Program.assertEqual(array, [2,3,5,6,7,9,10,11,12,14]);


# var swap = function(array, firstIndex, secondIndex) {
#     var temp = array[firstIndex];
#     array[firstIndex] = array[secondIndex];
#     array[secondIndex] = temp;
# };

# var partition = function(array, p, r) {
#     var q=p;
#     for (var j = p; j < r; j++) {
#         if (array[j] <= array[r]) {
#             swap(array, q, j);
#             q++;
#         }
#     }
#     swap(array,j,q);
#     return q;
# };

In [303]:
def quick_sort(array):
    p = 0
    r = len(array) -1
    merge_sort_(array, p, r)

def quick_sort_(array, p, r):
    #if the sub array is bigger then size 1
    if p-r > 1:
        #then partition it
        q = partition(array, p, r)
        #call quick sort on the resulting halves
        quick_sort_(array, p, q)
        quick_sort_(array, q, r)


def partition(array, p, r):
    pivot_val = array[r]
    
    j = p
    q  = p
    
    for j, val in enumerate(array[p:r], p):
        if val < pivot_val: 
            swap(array, q, j)
            q += 1
    swap(q,r)
    return q

def swap(array, first_index, second_index):
    #swaps the elements at the given indexes of the array
    temp = array[first_index]
    array[first_index] = array[second_index]
    array[first_index] = temp

In [304]:
sorted_array = np.arange(2,20)
sorted_array[0] = -5
unsorted_array = np.random.permutation(sorted_array.copy())
print(unsorted_array)
print(sorted_array)

quick_sort(unsorted_array)
print(unsorted_array)
assert np.array_equal(unsorted_array, sorted_array)

[10 13  7 17 -5 18 11  6 15  8 19 14 12  9  5  3 16  4]
[-5  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-5  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [312]:
def is_palindrome(str):
    #base 1
    if len(str) == 0 or len(str) == 1:
        return True
    elif str[0] != str[-1]:
        return False
    else:
        return is_palindrome(str[1:-1])
assert is_palindrome('a')
assert ~is_palindrome('az')
assert is_palindrome('ysaeeasy')

Quick sort

Strategy:
Sort subarray arr[p:r] of the array
Start with subarray arr[0:r]

divide:
choose a pivot in the sub array, move elements greater than pivot to right, and less than the pivot to the left of the pivot. By convention choose the pivot was the right most element.

conquer:
recursively sort the left and right side of the pivot.

base case is arrays of less than 2. I.e. 1 and zero
